services:
    formula-frontend:
        container_name: dashboard-formula-frontend
        restart: always
        build:
            context: ./
        ports:
            - '3014:3000'
        networks:
            - network-formula
        working_dir: /app
        command: sh -c "yarn install && yarn dev "
        volumes:
            - .:/app
        tty: true

networks:
    network-formula:
        name: network-formula
        external: true
