services:
    sounder:
        container_name: sounder-frontend
        restart: always
        build:
            context: ./
        ports:
            - '3000:3000'
        networks:
            - network-sounder
        working_dir: /app
        command: sh -c "yarn install && yarn dev "
        volumes:
            - .:/app
        tty: true

networks:
    network-sounder:
        name: network-sounder
